In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
raw_data = pd.read_csv('Data/1.03. Dummies.csv')

In [4]:
raw_data.head()

SAT   GPA Attendance
0  1714  2.40         No
1  1664  2.52         No
2  1760  2.54         No
3  1685  2.74         No
4  1693  2.83         No

In [5]:
data = raw_data.copy()

In [6]:
data['Attendance'] = data['Attendance'].map({'Yes':1,'No':0})

In [7]:
data.head()

SAT   GPA  Attendance
0  1714  2.40           0
1  1664  2.52           0
2  1760  2.54           0
3  1685  2.74           0
4  1693  2.83           0

In [14]:
data.head()

SAT   GPA  Attendance
0  1714  2.40           0
1  1664  2.52           0
2  1760  2.54           0
3  1685  2.74           0
4  1693  2.83           0

In [15]:
x1 = data[['SAT','Attendance']]
y = data['GPA']
#Standarding the data
Scaler = StandardScaler()
Scaler.fit(x1)

StandardScaler()

In [16]:
data_scaled = Scaler.transform(x1)

In [22]:
#Spliting
x_train, x_test, y_train, y_test = train_test_split(data_scaled,y,test_size=0.2,random_state=42)

In [26]:
x_test

array([[ 0.85390339,  1.07417231],
       [-1.26338288, -0.93094934],
       [-0.61857297,  1.07417231],
       [-1.75420834, -0.93094934],
       [-1.06127829, -0.93094934],
       [ 0.84427936,  1.07417231],
       [-1.06127829, -0.93094934],
       [-0.03150724, -0.93094934],
       [-1.46548748, -0.93094934],
       [-0.12774752,  1.07417231],
       [ 0.18984542, -0.93094934],
       [ 1.06563201, -0.93094934],
       [ 0.03586096, -0.93094934],
       [ 1.3639769 , -0.93094934],
       [ 0.40157405,  1.07417231],
       [ 0.32458182,  1.07417231],
       [ 0.09360513,  1.07417231]])

In [27]:
# Regression
reg = LinearRegression()

In [28]:
reg.fit(x_train,y_train)

LinearRegression()

In [29]:
#Coefficient and Intercept
reg.coef_, reg.intercept_

(array([0.12932989, 0.11232211]), 3.3337771004692014)

In [36]:
#Creating Summary Table
Summary_table = pd.DataFrame([['SAT'],['Attendance'],['Intercept']], columns=['Features'])

In [38]:
Summary_table['Weights'] = reg.coef_[0],reg.coef_[1],reg.intercept_

In [39]:
Summary_table

Features   Weights
0         SAT  0.129330
1  Attendance  0.112322
2   Intercept  3.333777

In [41]:
#F statistics
reg.score(x_train,y_train)

0.5527042278878489

In [43]:
Summary_table

Features   Weights  F Statistic/ R-Squared
0         SAT  0.129330                0.552704
1  Attendance  0.112322                0.552704
2   Intercept  3.333777                0.552704

In [44]:
#Feature Selection
from sklearn.feature_selection import f_regression

In [46]:
f_regression(x_train,y_train)

(array([37.96161426, 27.81731863]), array([5.10187427e-08, 1.63369267e-06]))

In [63]:
reg_summary = pd.DataFrame([['SAT'],['Attendance']], columns=['Features'])
reg_summary['Weights'] = reg.coef_[0],reg.coef_[1]

In [59]:

reg_summary
p_value = f_regression(x_train,y_train)[1]
p_value

array([5.10187427e-08, 1.63369267e-06])

In [72]:
reg_summary['P-values'] = p_value.round(3)

In [73]:
reg_summary

Features   Weights  P-values
0         SAT  0.129330       0.0
1  Attendance  0.112322       0.0

In [81]:
#Prediction
pred = reg.predict(x_test)

In [88]:
table = x_test.copy()
pred = pd.DataFrame(pred)
table = pd.DataFrame(table)
pred

0
0   3.564866
1   3.065818
2   3.374430
3   3.002339
4   3.091956
5   3.563621
6   3.091956
7   3.225136
8   3.039680
9   3.437909
10  3.253764
11  3.367029
12  3.233849
13  3.405614
14  3.506366
15  3.496409
16  3.466536

In [89]:
table['Predictions'] = pred

In [90]:
table

0         1  Predictions
0   0.853903  1.074172     3.564866
1  -1.263383 -0.930949     3.065818
2  -0.618573  1.074172     3.374430
3  -1.754208 -0.930949     3.002339
4  -1.061278 -0.930949     3.091956
5   0.844279  1.074172     3.563621
6  -1.061278 -0.930949     3.091956
7  -0.031507 -0.930949     3.225136
8  -1.465487 -0.930949     3.039680
9  -0.127748  1.074172     3.437909
10  0.189845 -0.930949     3.253764
11  1.065632 -0.930949     3.367029
12  0.035861 -0.930949     3.233849
13  1.363977 -0.930949     3.405614
14  0.401574  1.074172     3.506366
15  0.324582  1.074172     3.496409
16  0.093605  1.074172     3.466536