In [69]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import f_regression
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn import metrics
#pd.set_option('display.mpl_style','default')
plt.rcParams['figure.figsize'] = (15,5)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
#Viewing Summary()
from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq,df)

In [2]:
raw_data = pd.read_csv('nba.csv')

In [4]:
# the independent variables set 
X = raw_data[['GP','3P Made', '3PA', 'AST', 'BLK','TOV']]
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 
  
print(vif_data)

   feature        VIF
0       GP   5.621731
1  3P Made  41.542536
2      3PA  46.371652
3      AST   6.391056
4      BLK   2.541630
5      TOV  12.631371


In [20]:
# the independent variables set 
X1 = raw_data[['GP', '3PA', 'AST', 'BLK']]
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X1.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X1.values, i) 
                          for i in range(len(X1.columns))] 
  
print(vif_data)

  feature       VIF
0      GP  4.134206
1     3PA  1.854798
2     AST  2.946362
3     BLK  2.008172


In [21]:
# the independent variables set 
X2 = raw_data[['GP', 'AST', 'BLK']]
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X2.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X2.values, i) 
                          for i in range(len(X2.columns))] 
  
print(vif_data)

  feature       VIF
0      GP  3.922528
1     AST  2.552487
2     BLK  1.967612


In [24]:
# the independent variables set 
X3 = raw_data[['GP','3P Made', 'AST', 'BLK']]
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X3.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X3.values, i) 
                          for i in range(len(X3.columns))] 
  
print(vif_data)

   feature       VIF
0       GP  4.088346
1  3P Made  1.664277
2      AST  2.863462
3      BLK  2.004278


### For X1 VIF Group

In [25]:
inputs = X1.copy()
inputs

GP  3PA  AST  BLK
0     36  2.1  1.9  0.4
1     35  2.8  3.7  0.5
2     74  1.7  1.0  0.3
3     58  0.5  0.8  0.1
4     48  0.1  0.3  0.4
...   ..  ...  ...  ...
1335  80  0.2  2.5  0.2
1336  68  0.7  2.3  0.0
1337  43  0.0  0.3  0.4
1338  52  0.2  2.2  0.1
1339  47  1.3  1.4  0.1

[1340 rows x 4 columns]

In [27]:
target = raw_data['TARGET_5Yrs']

### Logistic Regression (Using Statsmodel)

In [32]:
x1 = sm.add_constant(inputs)
results1 = sm.Logit(target,x1).fit()
results1.summary()

Optimization terminated successfully.
         Current function value: 0.571539
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:            TARGET_5Yrs   No. Observations:                 1340
Model:                          Logit   Df Residuals:                     1335
Method:                           MLE   Df Model:                            4
Date:                Tue, 05 Jan 2021   Pseudo R-squ.:                  0.1392
Time:                        17:46:05   Log-Likelihood:                -765.86
converged:                       True   LL-Null:                       -889.75
Covariance Type:            nonrobust   LLR p-value:                 1.968e-52
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.4809      0.229    -10.855      0.000      -2.929      -2.033
GP             0.0423      0.004     10.139      0.000       0.034       0.050
3PA           -0.0679      0.066     -1.022      0.307      -0.198       0.062
AST            0.1477      0.057      2.588      0.010       0.036       0.260
BLK            0.9516      0.206      4.615      0.000       0.547       1.356
==============================================================================
"""

In [33]:
pred1 = results1.pred_table()

In [34]:
pred1

array([[265., 244.],
       [151., 680.]])

In [35]:
cm_df1 = pd.DataFrame(pred1)
cm_df1.columns = ['Predicted 0', 'Predicted 1']
cm_df1 = cm_df1.rename(index={0:'Actual 0', 1:'Actual 1'})
cm_df1

Predicted 0  Predicted 1
Actual 0        265.0        244.0
Actual 1        151.0        680.0

In [36]:
#Accuracy
cm1 = np.array(cm_df1)
accuracy_train1 = (cm1[0,0]+cm1[1,1])/cm1.sum()
accuracy_train1

0.7052238805970149

#### Testing

In [40]:
test_data1 = X1.copy()

In [41]:
test_data1 = sm.add_constant(test_data1)

In [42]:
test_data1

const  GP  3PA  AST  BLK
0       1.0  36  2.1  1.9  0.4
1       1.0  35  2.8  3.7  0.5
2       1.0  74  1.7  1.0  0.3
3       1.0  58  0.5  0.8  0.1
4       1.0  48  0.1  0.3  0.4
...     ...  ..  ...  ...  ...
1335    1.0  80  0.2  2.5  0.2
1336    1.0  68  0.7  2.3  0.0
1337    1.0  43  0.0  0.3  0.4
1338    1.0  52  0.2  2.2  0.1
1339    1.0  47  1.3  1.4  0.1

[1340 rows x 5 columns]

In [43]:
#create a function
def confusion_matrix(data, actual_values,model):
    pred_values = model.predict(data)
    bins = np.array([0,0.5,1])
    cm = np.histogram2d(actual_values,pred_values, bins = bins)[0]
    accuracy = (cm[0,0] + cm[1,1]/cm.sum())
    return cm,accuracy

In [45]:
cm = confusion_matrix(test_data1, target,results1)

In [46]:
cm

(array([[265., 244.],
        [151., 680.]]),
 265.5074626865672)

#### Using scikit learn

In [ ]:
target = raw_data['TARGET_5Yrs']
inputs

In [63]:
model1 = LogisticRegression(solver='liblinear',random_state=0).fit(inputs,target)

In [64]:
model1.coef_, model1.intercept_

(array([[ 0.04058706, -0.07247622,  0.14762157,  0.90660839]]),
 array([-2.35625676]))

In [65]:
results1.params

const   -2.480893
GP       0.042291
3PA     -0.067916
AST      0.147680
BLK      0.951602
dtype: float64

In [66]:
sum_table = pd.DataFrame(inputs.columns.values, columns=['Features'])
#sum_table['Weights'] = model.coef_
sum_table['F-stats'] = f_regression(inputs,target)[0].round(3)
sum_table['P-values'] = f_regression(inputs,target)[1].round(3)
#sum_table['Weights'] = model.coef_
sum_table
sum_table

Features  F-stats  P-values
0       GP  250.086     0.000
1      3PA    0.439     0.508
2      AST   42.447     0.000
3      BLK   61.798     0.000

In [70]:
confusion_matrix(target,model1.predict(inputs))

array([[261, 248],
       [148, 683]], dtype=int64)

In [73]:
cm = pd.DataFrame(confusion_matrix(target, model1.predict(inputs)))
cm.columns = ['Predicted 0', 'Predicted 1']
cm = cm.rename(index={0:'Actual 0', 1:'Actual 1'})
cm

Predicted 0  Predicted 1
Actual 0          261          248
Actual 1          148          683

In [74]:
#Accuracy
cm1 = np.array(cm)
accuracy_train = (cm1[0,0]+cm1[1,1])/cm1.sum()
accuracy_train

0.7044776119402985

In [75]:
## Classification Report
print(classification_report(target, model1.predict(inputs)))

              precision    recall  f1-score   support

         0.0       0.64      0.51      0.57       509
         1.0       0.73      0.82      0.78       831

    accuracy                           0.70      1340
   macro avg       0.69      0.67      0.67      1340
weighted avg       0.70      0.70      0.70      1340

